<?php

/**
 * PluginConfigValueTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginConfigValueTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return PluginConfigValueTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginConfigValue');
    }
}